In [12]:
import pandas as pd

data=pd.read_csv("data/raw/2025.csv")
df=pd.DataFrame(data)

df.head()

,Unnamed: 0,title,description,directed_by,written_by,produced_by,starring,cinematography,edited_by,release_date,country,language
0,0,$10 Cowboy,$10 Cowboy is the twelfth album by American si...,Patrick Heaphy,NaN,"Son of Davy, LCM247","Charley Crockett, Taylor Day Grace, The Blue D...",NaN,NaN,"October 24, 2025(Austin Film Festival)",United States,English
1,1,2K Love Story,2K Love Story is a 2025 Indian Tamil-language ...,Suseenthiran,Suseenthiran,"Vignesh Subramanian, G. Dhananjayan, (presenter)","Jagaveer, Meenakshi Govindarajan, Bala Saravanan",V. S. Anandha Krishna,Thiyagu,14 February 2025,India,Tamil
2,2,3BHK,3BHK[a] is a 2025 Indian Tamil-language coming...,Sri Ganesh,NaN,Arun Viswa,"Siddharth, R. Sarathkumar, Devayani, Meetha Ra...","Dinesh B. Krishnan, Jithin Stanislaus",Ganesh Siva,4 July 2025,India,Tamil
3,3,The 4 Rascals,The film revolves around a love triangle.,Tran Thanh,NaN,NaN,"Tran Thanh, Le Duong Bao Lam, Le Giang, Uyen A...",NaN,NaN,29 January 2025(Vietnam),Vietnam,Vietnamese
4,4,4 Tigers,"This film is part of the Khun Pan universe, se...",Kongkiat Komesiri,"Sukosin Akkrapat, Nakarin Gakhan, Kongkiat Kom...",Somsak Techarattanaprasert,"Sukollawat Kanaros, Mario Maurer, Arak Amornsu...",NaN,NaN,"October 23, 2025",Thailand,"Thai, Teochew"

In [10]:
print(df.shape)
print(df.columns)
print(df.info())

(2633, 12)
Index(['Unnamed: 0', 'title', 'description', 'directed_by', 'written_by',
       'produced_by', 'starring', 'cinematography', 'edited_by',
       'release_date', 'country', 'language'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 2633 entries, 0 to 2632
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      2633 non-null   int64
 1   title           2633 non-null   str
 2   description     2608 non-null   str
 3   directed_by     2540 non-null   str
 4   written_by      1662 non-null   str
 5   produced_by     2394 non-null   str
 6   starring        2357 non-null   str
 7   cinematography  2228 non-null   str
 8   edited_by       2199 non-null   str
 9   release_date    2545 non-null   str
 10  country         2511 non-null   str
 11  language        2484 non-null   str
dtypes: int64(1), str(11)
memory usage: 247.0 KB
None

In [11]:
df["description"].sample(3, random_state=42).tolist()

['Locked is a 2025 American psychological thriller film directed by David Yarovesky and written by Michael Arlen Ross. It is a remake of the Argentine film 4x4 (2019).[4][5][6]',
 'Marutha is a 2025 Indian Kannada-language action thriller film directed by filmmaker S. Narayan.[1] Produced under the banner Eashaa Productions by K. Manju and Ramesh Yadav, the film has an ensemble cast including Duniya Vijay, Shreyas Manju, V. Ravichandran, Brinda Acharya, Nishvika Naidu, Tara and Rangayana Raghu in pivotal roles.[2]',
 'The project began with an open call aimed at people skeptical of mainstream media coverage of the war. From around sixty applicants, three participants were selected: Ivo, Nikola, and Petra—who described themselves as "dezoláti" (a Czech pejorative for naïve conspiracy believers; loosely translatable as loony).[2][3] In October 2024 they traveled by minibus from Prague to the Donbas, visiting cities such as Kharkiv and the area around Izium.[1]']

In [4]:
import pandas as pd
from ingestion import load_movies, RAW_DATA_PATH

df = pd.read_json("/workspaces/llm-zoomcamp-course/code/final_proj_test/data/processed/documents.json")

df.head()

   id          title                                            content
0   0     $10 Cowboy  Title: $10 Cowboy\n\nDescription: $10 Cowboy i...
1   1  2K Love Story  Title: 2K Love Story\n\nDescription: 2K Love S...
2   2           3BHK  Title: 3BHK\n\nDescription: 3BHK[a] is a 2025 ...
3   3  The 4 Rascals  Title: The 4 Rascals\n\nDescription: The film ...
4   4       4 Tigers  Title: 4 Tigers\n\nDescription: This film is p...

In [13]:
search_term = '2024'
found_documents = df[df['content'].str.contains(search_term, case=False, na=False)]
print(f"\nDocuments containing '{search_term}':")
print(found_documents)

Documents containing '2024':
          id                                             title  \
0          0                                        $10 Cowboy
72        72                                         Afterburn
101      101                                           Alifaan
239      239                                             Barni
246      246                     Be Forever Yamato: Rebel 3199
...      ...                                               ...
29640  29640  Hayflower, Quiltshoe and the Feisty First-grader
29787  29787                       The Island of Giant Insects
30276  30276                                          OK Chlöe
30492  30492                Revue Starlight: Rondo Rondo Rondo
30987  30987                                      Welcome Home

                                                 content
0      Title: $10 Cowboy\n\nDescription: $10 Cowboy i...
72     Title: Afterburn\n\nDescription: Afterburn is ...
101    Title: Alifaan\n\nDescription: Following the r...
239    Title: Barni\n\nDescription: Sheikh moved to M...
246    Title: Be Forever Yamato: Rebel 3199\n\nDescri...
...                                                  ...
29640  Title: Hayflower, Quiltshoe and the Feisty Fir...
29787  Title: The Island of Giant Insects\n\nDescript...
30276  Title: OK Chlöe\n\nDescription: Chlöe Charlott...
30492  Title: Revue Starlight: Rondo Rondo Rondo\n\nD...
30987  Title: Welcome Home\n\nDescription: Welcome Ho...

[3235 rows x 3 columns]